---
apiVersion: v1
kind: Service
metadata:
  name: test1
  namespace: fika
  labels:
    app: test1
    service: test1
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: test1